/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package madreteresacrud;

import java.awt.Dimension;
import java.beans.Beans;
import java.math.BigDecimal;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.persistence.RollbackException;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import madreteresacrud.floresVida.FlorVidaABM;
import madreteresacrud.floresVida.SociosFVABM;
import reportes.IngresosEgresos;

/**
 *
 * @author leandro
 */
public class MadreTeresaMain extends javax.swing.JFrame {

    /**
     * Creates new form MadreTeresaMain
     */  
    
    //static JDesktopPane dp = new JDesktopPane();
    public MadreTeresaMain() {
        super("Sistema Madre Teresa de Calcuta");        
        initComponents();    
        
        JInternalFrame internal =  new JInternalFrame("Socios");
        JPanel p = new SociosABM();
        internal.add(p);          
        internal.pack();
        internal.setResizable(true);        
        internal.setClosable(true);    
          
        jDesktopPane.add(internal);         
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.getContentPane().add(jDesktopPane);        
          internal.setVisible(true); 
        
        this.setLocationRelativeTo(null); 
        this.setVisible(true);  

         jDesktopPane.setSize(this.getSize().width, this.getSize().height);
         jDesktopPane.repaint();  
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuSocios = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuDonaciones = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuGastos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu4.setText("Socios");

        jMenuSocios.setText("Gestionar Socios");
        jMenuSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSociosActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuSocios);

        jMenuItem3.setText("Montos de Cuotas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Ingresos");

        jMenuDonaciones.setText("Registrar Donaciones");
        jMenuDonaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDonacionesActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuDonaciones);

        jMenuItem7.setText("Registrar Evento");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem5.setText("Registrar Flores de Vida");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuItem6.setText("Registrar Cuotas de Flores de Vida");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Gastos");

        jMenuGastos.setText("Registrar Gastos");
        jMenuGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGastosActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuGastos);

        jMenuItem1.setText("Tipos de Gastos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuBar1.add(jMenu7);

        jMenu1.setText("Informes");

        jMenuItem4.setText("Emitir Informe");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSociosActionPerformed
        JInternalFrame internal =  new JInternalFrame("Socios");
        JPanel p = new SociosABM();
        internal.add(p);          
        internal.pack();
        internal.setResizable(true);        
        internal.setClosable(true);    
        jDesktopPane.removeAll();
        jDesktopPane.add(internal);
        jDesktopPane.repaint();
        internal.setVisible(true); 
        
//        JFrame frame = new JFrame("Socios");
//        frame.setContentPane(new SociosABM());
//        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        frame.pack();
//        frame.setVisible(true);
//        frame.setLocationRelativeTo(null);
            
    }//GEN-LAST:event_jMenuSociosActionPerformed

    private void jMenuDonacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDonacionesActionPerformed
        JInternalFrame internal =  new JInternalFrame("Donaciones");
        JPanel p = new DonacionesABM();
        internal.add(p);          
        internal.pack();
        internal.setResizable(true);        
        internal.setClosable(true);    
        jDesktopPane.removeAll();
        jDesktopPane.add(internal);
        jDesktopPane.repaint();
        internal.setVisible(true); 
        
//        JFrame frame = new JFrame("Donaciones");
//        frame.setContentPane(new DonacionesABM());
//        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        frame.pack();
//        frame.setVisible(true);
//        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuDonacionesActionPerformed

    private void jMenuGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGastosActionPerformed
        JInternalFrame internal =  new JInternalFrame("Gastos");
        JPanel p = new GastosABM();
        internal.add(p);          
        internal.pack();
        internal.setResizable(true);        
        internal.setClosable(true);    
        jDesktopPane.removeAll();
        jDesktopPane.add(internal);
        jDesktopPane.repaint();
        internal.setVisible(true); 
        
//        JFrame frame = new JFrame("Gastos");
//        frame.setContentPane(new GastosABM());
//        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        frame.pack();
//        frame.setLocationRelativeTo(null);
//        frame.setVisible(true);
       
    }//GEN-LAST:event_jMenuGastosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JInternalFrame internal =  new JInternalFrame("Tipos de Gastos");
        JPanel p = new TipoGastoABM();
        internal.add(p);          
        internal.pack();
        internal.setResizable(true);        
        internal.setClosable(true);    
        jDesktopPane.removeAll();
        jDesktopPane.add(internal);
        jDesktopPane.repaint();
        internal.setVisible(true); 
        
//        JFrame frame = new JFrame("Tipos de Gastos");
//        frame.setContentPane(new TipoGastoABM());
//        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        frame.pack();
//        frame.setLocationRelativeTo(null);
//        frame.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        JInternalFrame internal =  new JInternalFrame("Montos de Cuotas");
        JPanel p = new TipoSocioABM();
        internal.add(p);          
        internal.pack();
        internal.setResizable(true);        
        internal.setClosable(true);    
        jDesktopPane.removeAll();
        jDesktopPane.add(internal);
        jDesktopPane.repaint();
        internal.setVisible(true);
        
        //        JFrame frame = new JFrame("Tipos de Socios");
//        frame.setContentPane(new TipoSocioABM());
//        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        frame.pack();
//        frame.setLocationRelativeTo(null);
//        frame.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         IngresosEgresos ing = new IngresosEgresos();
         ing.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
         ing.setLocationRelativeTo(null);
         ing.setVisible(true);
         
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JInternalFrame internal =  new JInternalFrame("Flores de vida");
        JPanel p = new FlorVidaABM();
        internal.add(p);          
        internal.pack();
        internal.setResizable(true);        
        internal.setClosable(true);    
        jDesktopPane.removeAll();
        jDesktopPane.add(internal);
        jDesktopPane.repaint();
        internal.setVisible(true);
        
//        JFrame frame = new JFrame("Flores de vida");
//        frame.setContentPane(new FlorVidaABM());
//        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        frame.pack();
//        frame.setLocationRelativeTo(null);
//        frame.setVisible(true);
      
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JInternalFrame internal =  new JInternalFrame("Aderentes de flores de vida");
        JPanel p = new SociosFVABM();
        internal.add(p);          
        internal.pack();
        internal.setResizable(true);        
        internal.setClosable(true);    
        jDesktopPane.removeAll();
        jDesktopPane.add(internal);
        jDesktopPane.repaint();
        internal.setVisible(true);
        
//        JFrame frame = new JFrame("Socios de flores de vida");
//         frame.setContentPane(new SociosFVABM());
//         frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//         frame.pack();
//         frame.setLocationRelativeTo(null);
//         frame.setVisible(true);
         
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JInternalFrame internal =  new JInternalFrame("Eventos");
        JPanel p = new EventosABM();
        internal.add(p);          
        internal.pack();
        internal.setResizable(true);        
        internal.setClosable(true);    
        jDesktopPane.removeAll();
        jDesktopPane.add(internal);
        jDesktopPane.repaint();
        internal.setVisible(true);
        
//        JFrame frame = new JFrame("Eventos");
//        frame.setContentPane(new EventosABM());
//        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        frame.pack();
//        frame.setLocationRelativeTo(null);
//        frame.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    public void generarCuotas(){
        SociosABM socios = new SociosABM();
        Socios s = new Socios();
        CuotaSocialABM cs;
        Date f = new Date();
        Date f2 = new Date();
        Calendar f1 = GregorianCalendar.getInstance(); 
        BigDecimal monto;
        TipoSocioABM ts = new TipoSocioABM();
        CuotaSocial c1 = new CuotaSocial();       
        
        java.util.Collection listaSocios = socios.getListaSocios();
        java.util.Collection listaCuotas;
        for(Object socio:listaSocios){
            s = (Socios)socio;
            CuotaSocial c = new CuotaSocial();
            monto = ts.getMonto(ts.getTipoSoc(s.getIdTipoSocio()));                   
            c.setMonto(monto);
            c.setIdSocio(s.getIdSocio());
            cs = new CuotaSocialABM(s.getIdSocio());
            cs.setQuery();
            listaCuotas = cs.getListaCuotas();
            if(listaCuotas.isEmpty()){
                f1.setTime(f);
                f1.set(Calendar.DAY_OF_MONTH,1);
                c.setFechaActivacion(f1.getTime());                 
                entityManager.persist(c);               
                //Guardamos la cuota
                try {
                    entityManager.getTransaction().commit();
                    entityManager.getTransaction().begin();
                } catch (RollbackException rex) {
                    rex.printStackTrace();
                    entityManager.getTransaction().begin();            
                }
                
            }else{
                for(Object cuota:listaCuotas){
                    c1 =(CuotaSocial)cuota;
                    f = c1.getFechaActivacion();  
                    if(f2.getMonth()>f.getMonth()){
                        f1.setTime(f);        
                        f1.add(Calendar.MONTH, 1); 
                        f1.set(Calendar.DAY_OF_MONTH,1);
                        c.setFechaActivacion(f1.getTime());                         
                        entityManager.persist(c);
                
                        //Guardamos la cuota
                        try {
                            entityManager.getTransaction().commit();
                            entityManager.getTransaction().begin();
                        } catch (RollbackException rex) {
                            rex.printStackTrace();
                            entityManager.getTransaction().begin();            
                        }
                    }
                    break;
                }
                              
                
            }
            
        }
        
    }
    public void setEntity(){
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("madreTeresaCRUDPU").createEntityManager();                 
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MadreTeresaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MadreTeresaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MadreTeresaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MadreTeresaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                MadreTeresaMain m  = new MadreTeresaMain(); 
                m.setEntity();
                m.generarCuotas();                                      
                 
            }
        });
    }
    private javax.persistence.EntityManager entityManager;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDonaciones;
    private javax.swing.JMenuItem jMenuGastos;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuSocios;
    // End of variables declaration//GEN-END:variables

}
